<?php
return [
    'commands' => [
        'db:check-tables' => \app\command\CheckDatabaseTables::class,
        'db:check-data' => \app\command\CheckDatabaseData::class,
        'db:export-schema' => \app\command\ExportDatabaseSchema::class,
        'db:fix-missing-tables' => \app\command\FixMissingTables::class,
        'db:create-alias-tables' => \app\command\CreateAliasTables::class,
        'db:preview-clean' => \app\command\PreviewCleanExtraTables::class,
        'db:clean-extra-tables' => \app\command\CleanExtraTables::class,
        'db:drop-game-message' => \app\command\DropGameMessageTable::class,
        'db:restore-banner' => \app\command\RestoreBannerTable::class,
        'db:restore-help' => \app\command\RestoreHelpTable::class,
        'db:check-banner' => \app\command\CheckBannerTable::class,
        'db:restore-backup' => \app\command\RestoreBackupData::class,
        'db:restore-admin-log' => \app\command\RestoreAdminLogTable::class,
        'db:restore-product-category' => \app\command\RestoreProductCategoryTable::class,
        'db:restore-remaining' => \app\command\RestoreRemainingTables::class,
        'db:restore-all-deleted' => \app\command\RestoreAllDeletedTables::class,
        'test:create-user' => \app\command\CreateTestUser::class,
        'admin:create' => \app\command\CreateAdmin::class,
        'admin:create-table' => \app\command\CreateAdminTable::class,
        'auto:close_order' => \app\command\AutoCloseOrder::class,
        'auto:complete_order' => \app\command\AutoCompleteOrder::class,
        'auto:start_order' => \app\command\AutoStartOrder::class,
        'auto:clean_expired_orders' => \app\command\CleanExpiredOrders::class,
        'auto:check_device_offline' => \app\command\CheckDeviceOffline::class,
        'auto:backup_database' => \app\command\BackupDatabase::class,
        'auto:check_system_health' => \app\command\CheckSystemHealth::class,
        'sync:room-status' => \app\command\SyncRoomStatus::class,
    ],
];
